### ISSUE TITLE
Network management issue

### ISSUE THREAD

**Issue by gamma63** [Vardan2009/radiant#4]
@Vardan2009 problem was in network, when I am moved network stuff from source folder, all was builded successfully

**Comment by gamma63** [comment]
You need to use Cosmos TCP **Client** instead of dotnet one

**Comment by Vardan2009** [comment]
What cosmos are you using? Devkit or Userkit?

**Comment by gamma63** [comment]
Devkit

**Comment by gamma63** [comment]
So [this problem](https://github.com/CosmosOS/Cosmos/issues/3046) was caused by Network Management, not by events

**Comment by Vardan2009** [comment]
No, my problem was different from this one. When i remove the events, it all gets compiled correctly. Cosmos was just missing a plug for System.MulticastDelegate

**Comment by Vardan2009** [comment]
> You need to use Cosmos TCP **Client** instead of dotnet one

Could you provide more details on this?

**Comment by gamma63** [comment]
As I am understand the dotnet tcp stack will not work, you need to use stuff from the Cosmos itself

**Comment by gamma63** [comment]
here is tcp namespace: Cosmos.System.Network.IPv4.TCP

**Comment by Vardan2009** [comment]
> As I am understand the dotnet tcp stack will not work, you need to use stuff from the Cosmos itself

Cosmos has an implementation (plug) for the dotnet TCP stack (namespaces like `System.Net.Sockets`) and it runs without errors (for me at least).
I think the problem from your Cosmos setup, maybe you have an older version? I don't really know

**Comment by gamma63** [comment]
I will rebuild devkit to latest commit right now

**Comment by gamma63** [comment]
I have tried to build it without Events same issue as in #3046 from Cosmos repo, but when I am moving the network stuff, all is building properly

**Comment by gamma63** [comment]
this is really strange

**Comment by Vardan2009** [comment]
That's really weird

**Comment by gamma63** [comment]
UPD: When I am tried to build it with Github Actions same issue

**Comment by gamma63** [comment]
![image](https://github.com/user-attachments/assets/2dbd9ca9-e7af-43e4-8067-a19aecb885a8)

**Comment by gamma63** [comment]
https://github.com/gamma63/radiant/actions/runs/10089496132/job/27897054722 (I don't know why github thinks it was successful.)

**Comment by Vardan2009** [comment]
> ![image](https://github.com/user-attachments/assets/2dbd9ca9-e7af-43e4-8067-a19aecb885a8)
> 
> 

That's the exact same error.
Maybe you can try changing the Github workflow from Ubuntu to Windows?

**Comment by gamma63** [comment]
I will try

**Comment by gamma63** [comment]
I am caught in a chicken and egg problem as I don't know how to build COSMOS on windows with github actions, since COSMOS has a graphical builder

**Comment by gamma63** [comment]
I am going to close it as wontfix

**Comment by zarlo** [comment]
> I am caught in a chicken and egg problem as I don't know how to build COSMOS on windows with github actions, since COSMOS has a graphical builder

https://github.com/CosmosOS/Cosmos/blob/master/.github/workflows/pr.yml should have every thing you need
